name: Build Signed Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Decode keystore from Base64 and save to file
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-release-key.jks

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build signed Release APK
      run: ./gradlew assembleRelease --no-daemon

    - name: List APK files recursively
      run: ls -R app/build/outputs/apk/

    - name: Upload signed APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-signed-apk
        path: app/build/outputs/apk/release/app-release.apk
